### ISSUE TITLE
Can't add App Folder

### ISSUE THREAD

**Issue by Dobbie03** [muflone/gnome-appfolders-manager#1]
I'm using Gnome-Shell 3.20 with Arch Linux and I can seem to add any app folders.  I can create them  in Appfolders Manager but when I quit the program nothing has changed, no apps have been moved to any folders.

**Comment by muflone** [comment]
Have you clicked the save button before closing the application?

**Comment by Dobbie03** [comment]
Bloody hell I feel so stupid.  No I didn't.  Thanks for the reply.

**Comment by muflone** [comment]
I'll add some hints to invite you to press the save button, as it actually it's not really clear.
I hope you like this application.

**Comment by Dobbie03** [comment]
Some hints would be really handy for silly people like me :)
