### ISSUE TITLE
Crash when not run as root

### ISSUE THREAD

**Issue by VerusGott** [muflone/gnome-appfolders-manager#13]
I have no idea what's wrong with that. My system is Arch Linux, package installed from AUR (tried both, stable and -git version). For the first time when I launched it just after install, it worked, but after closing app  it doesn't seem like it's going to work. It's crashes without any output to console. Here is the trace:
https://pastebin.com/pBTtvqU8

**Comment by muflone** [comment]
GNOME AppFolders Manager was rewritten in Python 3 since the version 0.4.0
Please test if you have the same issue in the newer versions
