### ISSUE TITLE
Huge blank sidebars small icons and text

### ISSUE THREAD

**Issue by jrlepage** [muflone/gnome-appfolders-manager#21]
Hello ever since installing this extension, my apps launcher has gigantic, blank side bars (where you can apparently drag to create new folder). It has made all the icons squished to the middle third of the screen, and the text is now so small that you can only read the first few letters. 

The worst part is this persists even after removing the extension. The first time I removed it, the apps went back to normal, but now it has persisted even after removing. Please help!

**Comment by muflone** [comment]
Hi

Are you sure that you installed my application?
GNOME AppFolders Manager is NOT a GNOME extension, that's a totally different application.

How did you installed, and uninstalled it?
