### ISSUE TITLE
Move about button to the menu

### ISSUE THREAD

**Issue by bilelmoussaoui** [muflone/gnome-appfolders-manager#3]
Can you please move the about button to the menu window? like other Gnome apps :+1: 
![capture du 2016-05-24 01-22-19](https://cloud.githubusercontent.com/assets/7660997/15487499/f9343442-214d-11e6-8c24-febfe6ff6a90.png)

**Comment by bilelmoussaoui** [comment]
It's already there, just need to be removed from the headerbar

**Comment by muflone** [comment]
What's the benefit in removing the about button from the headerbar?

**Comment by bilelmoussaoui** [comment]
To follow Gnome HIG:)

**Comment by muflone** [comment]
Actually I cannot see any enhancement in removing the about button from the headerbar.
Whenever I'll find stronger reasons, I'll think about.
