### ISSUE TITLE
Search functionnality

### ISSUE THREAD

**Issue by bilelmoussaoui** [muflone/gnome-appfolders-manager#4]
Have you planned to add Search functionnality to the application?

**Comment by muflone** [comment]
The application searching by typing the initial letters is already implemented, in both the main window and application picker dialog.

**Comment by bilelmoussaoui** [comment]
Well, in the main window it only works on the sidebar, i can't search inside of a folder. Maybe showing a search bar so the user can see that the functionnality exists ?

**Comment by muflone** [comment]
Fixed in 0.4.0
