### ISSUE TITLE
Screenshot in the README

### ISSUE THREAD

**Issue by kostich** [muflone/gnome-appfolders-manager#7]
You should add at least one screenshot to the README file. A good screenshot greatly increases the chance of someone using your program. You can add the screenshot [via this method](http://stackoverflow.com/a/10189374). I personally used the first line (relative path with ?raw=true parameter) in my repo so I recommend that way.

**Comment by muflone** [comment]
Great idea, I'll do very soon

**Comment by muflone** [comment]
Fixed in commit d2f1c9a
