### ISSUE TITLE
Show empty folders

### ISSUE THREAD

**Issue by bilelmoussaoui** [muflone/gnome-appfolders-manager#8]
As you can see in the screenshot the empty folders are not shown
![capture du 2016-06-03 22-03-11](https://cloud.githubusercontent.com/assets/7660997/15791335/0946bab2-29d7-11e6-9936-003be19e7360.png)

**Comment by muflone** [comment]
This application will list only the activated AppFolders, not the defined but disabled AppFolders.
To show them simply add a new AppFolders with the name of any disabled AppFolder.

**Comment by bilelmoussaoui** [comment]
Alright! i understand :+1: thanks for your answer
