### ISSUE TITLE
The possiblity to set folder cateogry

### ISSUE THREAD

**Issue by bilelmoussaoui** [muflone/gnome-appfolders-manager#9]
As you can see folders have a category key
Maybe providing a list of categories from where the user can choose one? 
![capture du 2016-06-03 22-04-58](https://cloud.githubusercontent.com/assets/7660997/15791375/3e7024e4-29d7-11e6-83bc-7550c4ee0c34.png)

**Comment by muflone** [comment]
The categories in the AppFolders are used to automatically include all the matching category applications, not to categorize the folders themselves.

I think the usage of the categories in place of the applications would cause many difficulties in the application usage.

**Comment by bilelmoussaoui** [comment]
Yeah i know. But imagine my case. I have a lot of installed games, the best way is to choose a cateogry for a folder instead of choosing each installed game, and whenever i install a new one i have to add it manually..

**Comment by muflone** [comment]
I'm not entirely sure to add this feature.
Categories surely will automatically pick up new applications with the defined categories but excluding a single application from a categorized AppFolders will result in a slight drawback, difficult to understand or handle for the end user.

Hints are welcomed
